arm:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.02
  goal_joint_tolerance: 0.002
  goal_position_tolerance: 0.002
  goal_orientation_tolerance: 0.02
  tip_name: tcp_link
